{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.6.jar",
          "url": "runelite-api-4.15.6.jar",
          "size": 1292209,
          "sha512": "98c0d0ec285d7ad7f1660a9721cd92b217bda66ae6f7b32f2f61fbe85b417698c2a206155f34695dab0923fec1b01d6f2e79d74a6e9e31db095a7c77bef42bb6",
          "sha256": "0a2c2e67653a0ae12dbf8989f1f6adedbb557ce9f2c487356c9e810fccbda680",
          "sha1": "187699ee359833966f098ff7546a5fe4da296e93",
          "md5": "dbb3a3097b64c31811689c3848efd75e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.6.jar",
          "url": "runelite-api-4.15.6.jar",
          "size": 1292209,
          "sha512": "98c0d0ec285d7ad7f1660a9721cd92b217bda66ae6f7b32f2f61fbe85b417698c2a206155f34695dab0923fec1b01d6f2e79d74a6e9e31db095a7c77bef42bb6",
          "sha256": "0a2c2e67653a0ae12dbf8989f1f6adedbb557ce9f2c487356c9e810fccbda680",
          "sha1": "187699ee359833966f098ff7546a5fe4da296e93",
          "md5": "dbb3a3097b64c31811689c3848efd75e"
        }
      ]
    }
  ]
}
