{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.6.jar",
          "url": "runescape-api-4.15.6.jar",
          "size": 113361,
          "sha512": "6db970a971e439df2209f440447d36f65c942b8885ab9508917d38dc4dd25c8441c0f687775fd86c8781751646956b5b4666809267df164442724e325eba5168",
          "sha256": "9557127f93c0bd76d5cb617c374f9d56e76d077c4e7e5acef1d583e44f5858f7",
          "sha1": "54cce54d5b6c5b3c2434ba642a470bbcf25d80c5",
          "md5": "90babc6f121691d89802ffb69e107c96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.6.jar",
          "url": "runescape-api-4.15.6.jar",
          "size": 113361,
          "sha512": "6db970a971e439df2209f440447d36f65c942b8885ab9508917d38dc4dd25c8441c0f687775fd86c8781751646956b5b4666809267df164442724e325eba5168",
          "sha256": "9557127f93c0bd76d5cb617c374f9d56e76d077c4e7e5acef1d583e44f5858f7",
          "sha1": "54cce54d5b6c5b3c2434ba642a470bbcf25d80c5",
          "md5": "90babc6f121691d89802ffb69e107c96"
        }
      ]
    }
  ]
}
