{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.4.jar",
          "url": "runelite-api-4.15.4.jar",
          "size": 1292087,
          "sha512": "5d9380affd052627276929d24a4975b77abd46c344f533db74f2ebcf06e6be15577831fe20ad10f77ca34d00a4a4b12e3827fe6b431a5bb11174783f2ad82ea3",
          "sha256": "7f87df5468207968d85d1766d7d73a10afa76e534d58da4fbeee7d2ba86dd5c8",
          "sha1": "2a61e94b99308a62c57d8f5e2fd1e2131d661bd1",
          "md5": "178913d91bc6fc5facf2742b94eaeadd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.4.jar",
          "url": "runelite-api-4.15.4.jar",
          "size": 1292087,
          "sha512": "5d9380affd052627276929d24a4975b77abd46c344f533db74f2ebcf06e6be15577831fe20ad10f77ca34d00a4a4b12e3827fe6b431a5bb11174783f2ad82ea3",
          "sha256": "7f87df5468207968d85d1766d7d73a10afa76e534d58da4fbeee7d2ba86dd5c8",
          "sha1": "2a61e94b99308a62c57d8f5e2fd1e2131d661bd1",
          "md5": "178913d91bc6fc5facf2742b94eaeadd"
        }
      ]
    }
  ]
}
