{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.16.1.jar",
          "url": "http-api-4.16.1.jar",
          "size": 160829,
          "sha512": "eab6c8c531c0a4b33afadc72f7c0fafa8bd0d48c7bca27d301d5c66378e0fea67b54c0b8359785e18370110880f46763eea34d193c54641b518d6ef62a2f74e1",
          "sha256": "15c5d9fb615484ad50ba6f15f362fda03ee1c60a86ed683550f6111c965be99c",
          "sha1": "21fc60b477ff4fb745a0cc4b45e75d42b209ddaf",
          "md5": "adb3d843bb723b53e9fb27a09aca80e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.16.1.jar",
          "url": "http-api-4.16.1.jar",
          "size": 160829,
          "sha512": "eab6c8c531c0a4b33afadc72f7c0fafa8bd0d48c7bca27d301d5c66378e0fea67b54c0b8359785e18370110880f46763eea34d193c54641b518d6ef62a2f74e1",
          "sha256": "15c5d9fb615484ad50ba6f15f362fda03ee1c60a86ed683550f6111c965be99c",
          "sha1": "21fc60b477ff4fb745a0cc4b45e75d42b209ddaf",
          "md5": "adb3d843bb723b53e9fb27a09aca80e5"
        }
      ]
    }
  ]
}
