{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.8.jar",
          "url": "http-api-4.15.8.jar",
          "size": 160828,
          "sha512": "98fda48178559228378670ce02a29331890fe1b5d7a84d54f34a2532d7c2f76cd990d2e71d4dc444fa395e288e256f248c3d56c0e76926b54db05631ff2c4093",
          "sha256": "53a38f046a261778ddf07ca5f1c4418dcb515c2d32e151d9553d6f4be00ccd35",
          "sha1": "f00befb4856aa1f0d8aeebaef6334ee7bafecbb1",
          "md5": "b665287816ac9e0d01fd4077068848d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.8.jar",
          "url": "http-api-4.15.8.jar",
          "size": 160828,
          "sha512": "98fda48178559228378670ce02a29331890fe1b5d7a84d54f34a2532d7c2f76cd990d2e71d4dc444fa395e288e256f248c3d56c0e76926b54db05631ff2c4093",
          "sha256": "53a38f046a261778ddf07ca5f1c4418dcb515c2d32e151d9553d6f4be00ccd35",
          "sha1": "f00befb4856aa1f0d8aeebaef6334ee7bafecbb1",
          "md5": "b665287816ac9e0d01fd4077068848d2"
        }
      ]
    }
  ]
}
