{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.4.jar",
          "url": "http-api-4.15.4.jar",
          "size": 160828,
          "sha512": "8d52ca9737301cf37867726145575895a15e5a962286ea594335edb2ff7ea5a841fadd6d3d8a4913f8e0e11d65ee498d574d11a2af2d0c04d70a22b662df4a6d",
          "sha256": "8ee307be03c9cfba2e41f9078d49503ba4ee3d338ef19738b3a6b40bbfbd4554",
          "sha1": "b04983bb58c79bffc083f36fc04ae1ec2e100151",
          "md5": "03b07ed58317297556c77a62446dc902"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.4.jar",
          "url": "http-api-4.15.4.jar",
          "size": 160828,
          "sha512": "8d52ca9737301cf37867726145575895a15e5a962286ea594335edb2ff7ea5a841fadd6d3d8a4913f8e0e11d65ee498d574d11a2af2d0c04d70a22b662df4a6d",
          "sha256": "8ee307be03c9cfba2e41f9078d49503ba4ee3d338ef19738b3a6b40bbfbd4554",
          "sha1": "b04983bb58c79bffc083f36fc04ae1ec2e100151",
          "md5": "03b07ed58317297556c77a62446dc902"
        }
      ]
    }
  ]
}
