{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.4.jar",
          "url": "http-api-4.15.4.jar",
          "size": 160829,
          "sha512": "887f684a82537552695f7d5b229644e9a2061aef91d7a23c5c69683f048a6734f243a1d28aea936309b414b8d6cdafd3a69f73eb492e8d28006fbc591b40cc80",
          "sha256": "ef661d4c6caddc2955cfd3cf2ac032baf5fe24e61ff9499830471bc0ac15f2b1",
          "sha1": "44b830be0dcb2a6ad42d25cdcf8385e14e3156d5",
          "md5": "0d56203558b7ef57cc43828eae17fd91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.4.jar",
          "url": "http-api-4.15.4.jar",
          "size": 160829,
          "sha512": "887f684a82537552695f7d5b229644e9a2061aef91d7a23c5c69683f048a6734f243a1d28aea936309b414b8d6cdafd3a69f73eb492e8d28006fbc591b40cc80",
          "sha256": "ef661d4c6caddc2955cfd3cf2ac032baf5fe24e61ff9499830471bc0ac15f2b1",
          "sha1": "44b830be0dcb2a6ad42d25cdcf8385e14e3156d5",
          "md5": "0d56203558b7ef57cc43828eae17fd91"
        }
      ]
    }
  ]
}
