{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.4.jar",
          "url": "http-api-4.15.4.jar",
          "size": 160828,
          "sha512": "4c32ba1156e0a7a429b42a7a57ed5895fca5deb9323e11e18936df1646602642fe7966a86d3a1445bb1d197715e5bf03b64e21e6ba5b5b35cb3afadadb009428",
          "sha256": "13c527b8401f64d92f558a4dba28c471bba0d2d8c0fb4430f5472423147601a6",
          "sha1": "89879539c7dfc49432a4eae82c6f8087fc82b94e",
          "md5": "ab7435c2d5f5c74fbcf7a4b12e9fc43c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.4.jar",
          "url": "http-api-4.15.4.jar",
          "size": 160828,
          "sha512": "4c32ba1156e0a7a429b42a7a57ed5895fca5deb9323e11e18936df1646602642fe7966a86d3a1445bb1d197715e5bf03b64e21e6ba5b5b35cb3afadadb009428",
          "sha256": "13c527b8401f64d92f558a4dba28c471bba0d2d8c0fb4430f5472423147601a6",
          "sha1": "89879539c7dfc49432a4eae82c6f8087fc82b94e",
          "md5": "ab7435c2d5f5c74fbcf7a4b12e9fc43c"
        }
      ]
    }
  ]
}
