{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.6.jar",
          "url": "http-api-4.15.6.jar",
          "size": 160828,
          "sha512": "98a93abfa4fe52e4e0b11527c81f14f95be0376b491b3c6399c3320290d0f85b32b235a49f9d9bffb3d9c0acd5195b834f7d548e646d9b03cbee72fe85848abb",
          "sha256": "27cafa057c774f645d2e36d71e5c5e633927152492d513552050407b4498d203",
          "sha1": "66430288321c78579d4ffe95de27a836b516e35b",
          "md5": "ada1c60f6bf590963820c76115f3af02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.6.jar",
          "url": "http-api-4.15.6.jar",
          "size": 160828,
          "sha512": "98a93abfa4fe52e4e0b11527c81f14f95be0376b491b3c6399c3320290d0f85b32b235a49f9d9bffb3d9c0acd5195b834f7d548e646d9b03cbee72fe85848abb",
          "sha256": "27cafa057c774f645d2e36d71e5c5e633927152492d513552050407b4498d203",
          "sha1": "66430288321c78579d4ffe95de27a836b516e35b",
          "md5": "ada1c60f6bf590963820c76115f3af02"
        }
      ]
    }
  ]
}
