{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.6.jar",
          "url": "http-api-4.15.6.jar",
          "size": 160828,
          "sha512": "0ac66f0d0b02dd1afc8991c61524ac55114185a0c20e4d9390368e7931b819e2536ed531964a637567ab1e668bf1ea17c5b5239a47a9d92690e211ac1d86eb9c",
          "sha256": "5be251de284a74de9a332fde2f22124e46d1d7ceba7912ffb3f06192d8237304",
          "sha1": "9366ffe331cbb234c96cbe124ae01c4fee26da0d",
          "md5": "0d6639ed6272f252f002e5baa8260e9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.6.jar",
          "url": "http-api-4.15.6.jar",
          "size": 160828,
          "sha512": "0ac66f0d0b02dd1afc8991c61524ac55114185a0c20e4d9390368e7931b819e2536ed531964a637567ab1e668bf1ea17c5b5239a47a9d92690e211ac1d86eb9c",
          "sha256": "5be251de284a74de9a332fde2f22124e46d1d7ceba7912ffb3f06192d8237304",
          "sha1": "9366ffe331cbb234c96cbe124ae01c4fee26da0d",
          "md5": "0d6639ed6272f252f002e5baa8260e9b"
        }
      ]
    }
  ]
}
